name: build-CI

on:
  push:
    branches:
    - ace
    - main
    - develop
    - feature/**
    - bugfix/**
    tags-ignore:
      - '**'
    paths-ignore:
      - 'README.md'

jobs:
  build:

    env:
      CONFIG: 'Release'
      SOLUTION: 'src/Ace.CSharp.Time.sln'
      TEST_PROJECT: 'src/tests/Ace.CSharp.Time.Tests/Ace.CSharp.Time.Tests.csproj'

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 6.0.x

    - name: dotnet restore
      run: dotnet restore $SOLUTION

    - name: dotnet build
      run: dotnet build $SOLUTION --configuration $CONFIG --no-restore

    - name: dotnet test
      run: dotnet test $TEST_PROJECT --configuration $CONFIG --no-restore --no-build --verbosity normal
